version: '3'
services:
  nginx:
    image: ${REGISTRY_ADDRESS}/nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - php-fpm
    ports:
    - "80:80"
  php-fpm:
    image: ${REGISTRY_ADDRESS}/php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      DATABASE_URL: pgsql://app:${DB_PASSWORD}@postges:5432/app
      MAILER_URL: null://localhost
  php-cli:
    image: ${REGISTRY_ADDRESS}/php-cli:${IMAGE_TAG}
    environment:
      DATABASE_URL: pgsql://app:${DB_PASSWORD}@postges:5432/app
      MAILER_URL: null://localhost
