version: '3'
services:
  nginx:
    build:
      context: project/docker/development
      dockerfile: nginx.dockerfile
    volumes:
    - ./project:/app
    depends_on:
      - php-fpm
    ports:
    - "8080:80"

  php-fpm:
    build:
      context: project/docker/development
      dockerfile: fpm.dockerfile
    volumes:
      - ./project:/app

  php-cli:
    build:
      context: project/docker/development
      dockerfile: cli.dockerfile
    volumes:
      - ./project:/app
      - composer:/root.composer/cache

volumes:
  composer: